### ISSUE TITLE
Posibility to run without log

### ISSUE THREAD

**Issue by edwvee** [liut/jpegquality#1]
Can you provide option for disable logging? Without disabling from outside like this:
```go
log.SetOutput(ioutil.Discard)
//jpegquality using
...
log.SetOutput(os.Stdout)
```

**Comment by edwvee** [comment]
Made a solution with logger object inside jpegReader and ability to predefine it's output before running New. Please, accept the pull request.

**Comment by liut** [comment]
Sorry for toooo late reply. I will redesign the logger part soon. and PRs is welcome.
